version: '3.9'
services:
  app:
    restart: always
    build: .
    env_file:
      - .env
    command: sh -c "uvicorn main:app --reload --host 0.0.0.0"
    logging:
      options:
        max-size: '500M'
        max-file: '5'
    ports:
      - '8001:8000'
    depends_on:
      - data_base
    volumes:
      - .:/app

  data_base:
    restart: always
    image: "postgres:11-alpine3.18"
    container_name: data_base
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5433:5432'
